{
  pkgs,
  lib,
  username,
  ...
}: {
  imports =
    [
      ../modules/nixos/disk-layout-options.nix
      ../modules/nixos/hardware.nix
      ../modules/nixos/security.nix
      ../modules/nixos/services.nix
      ../modules/nixos/desktop.nix
      ../modules/nixos/hyprland.nix
      ../modules/nixos/features/impermanence.nix
      ../modules/nixos/features/sops.nix
      ../modules/nixos/features/snapshots.nix
      ../modules/nixos/features/os-dashboard.nix
      ../modules/nixos/features/power.nix
    ]
    ++ lib.optional (builtins.pathExists ./deploy-config.nix) ./deploy-config.nix;

  networking.networkmanager.enable = true;
  hardware.enableRedistributableFirmware = true;
  services.resolved = {
    enable = true;
    settings = {
      Resolve = {
        DNSSEC = "allow-downgrade";
        DNSOverTLS = "opportunistic";
        DNS = "1.1.1.3#cloudflare-dns.com 9.9.9.9#dns.quad9.net";
        FallbackDNS = "8.8.8.8#dns.google";
      };
    };
  };
  boot.supportedFilesystems = ["ntfs"];

  # Always-on features
  features.impermanence.enable = true;
  features.os-dashboard.enable = true;

  # Defaults. Overridden by hosts/deploy-config.nix (generated by deploy.sh).
  # bootloader is intentionally NOT set here — its single source of truth is
  # deploy-config.nix, falling back to the option's own default in hardware.nix.
  diskLayout.withDualBoot = lib.mkDefault false;
  diskLayout.device = lib.mkDefault "/dev/sda";
  plymouthTheme = lib.mkDefault "dotted";

  console.keyMap = "de";

  time.timeZone = "Europe/Berlin";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.supportedLocales = [
    "en_US.UTF-8/UTF-8"
    "de_DE.UTF-8/UTF-8"
  ];

  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [
    stdenv.cc.cc
    zlib
    fuse3
    icu
    nss
    openssl
    curl
    expat
    libuuid
    libxcrypt-legacy
  ];

  nix.settings = {
    trusted-users = ["root" "@wheel"];
    auto-optimise-store = true;
    experimental-features = ["nix-command" "flakes"];
    min-free = 5 * 1024 * 1024 * 1024;
    max-free = 15 * 1024 * 1024 * 1024;
    substituters = [
      "https://cache.nixos.org"
      "https://nix-community.cachix.org"
    ];
    trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
    narinfo-cache-negative-ttl = 0;
    connect-timeout = 5;
    http-connections = 128;
    max-substitution-jobs = 128;
    warn-dirty = false;
    flake-registry = "";
  };

  programs.nh = {
    enable = true;
    clean.enable = true;
    clean.extraArgs = "--keep 5";
  };

  environment.sessionVariables = {
    NIX_CONFIG = "experimental-features = nix-command flakes";
  };

  users.users.${username} = {
    isNormalUser = true;
    description = "Muddy Black";
    extraGroups = ["networkmanager" "wheel" "libvirtd" "docker" "video" "render" "input"];
    shell = pkgs.zsh;
    initialPassword = "nixos";
  };

  programs.zsh = {
    enable = true;
    interactiveShellInit = "fastfetch";
  };

  environment.systemPackages = with pkgs; [
    vim
    wget
    git
    curl
    ripgrep
    pciutils
    usbutils
    lshw
    gnumake
    unzip
    zip
    unrar
    rar
    p7zip
    dnsutils
    fd
    wl-clipboard
    xclip
    ntfs3g

    sonomatic-sddm
    sweet-theme

    kdePackages.kdeplasma-addons
    kdePackages.spectacle
    kdePackages.ark
    kdePackages.sddm-kcm
    kdePackages.qtwebengine
  ];

  programs.kdeconnect.enable = true;
  programs.nix-index.enable = true;
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;
  };
  boot.tmp.cleanOnBoot = true;

  systemd.tmpfiles.rules = [
    "d /mnt/projects 0755 ${username} users -"
    "d /mnt/data 0755 ${username} users -"
  ];

  nixpkgs.config.allowUnfree = true;
  nixpkgs.config.permittedInsecurePackages = [
    "electron-37.10.3"
    "electron-39.8.10"
  ];

  system.stateVersion = "25.11";
}
