{
  pkgs,
  lib,
  config,
  username,
  ...
}: let
  cfg = config.features.desktops;
in {
  # Display & Desktop
  #
  # Everything here is Wayland: the greeter runs as a kwin_wayland compositor
  # (wayland.enable), and every session — Plasma 6, Hyprland, COSMIC, GNOME —
  # is a Wayland session. No X server is ever started.
  #
  # services.xserver.enable is therefore FALSE, and that is what drops the
  # "Plasma (X11)" entry from the greeter: plasma-workspace ships
  # xsessions/plasmax11.desktop unconditionally, but the sddm module only
  # writes the [X11] section — and with it SessionDir = …/share/xsessions —
  # when services.xserver.enable is true. Without that key SDDM falls back to
  # its compiled-in /usr/share/xsessions, which does not exist on NixOS, so it
  # lists Wayland sessions only.
  #
  # The German layout survives: /etc/X11/xorg.conf.d/00-keyboard.conf — what
  # systemd-localed, and therefore the greeter and XWayland clients, read — is
  # generated by services.graphical-desktop, which enables itself for
  # services.displayManager.enable and not just xserver.enable, and it still
  # reads services.xserver.xkb below.
  services.xserver.enable = false;
  services.displayManager.sddm = {
    enable = true;
    wayland.enable = true;
    # No `package` here on purpose: the Wayland greeter needs the Qt6 build,
    # and services.desktopManager.plasma6 now defines sddm.package as
    # kdePackages.sddm itself. Setting it again — even to that same
    # derivation — breaks eval, because the option takes a unique definition.
    theme = "Sonomatic";
    autoLogin.relogin = false;
    settings.General.InputMethod = "";
  };

  services.displayManager.autoLogin = {
    enable = false;
    user = null;
  };
  services.desktopManager.plasma6.enable = cfg.plasma.enable;
  # No X11 session left to drive, so its compositor is dead weight.
  environment.plasma6.excludePackages = [pkgs.kdePackages.kwin-x11];
  environment.systemPackages = lib.optional cfg.plasma.enable (
    pkgs.writeShellScriptBin "kde-plasma" ''
      exec ${pkgs.kdePackages.plasma-workspace}/libexec/plasma-dbus-run-session-if-needed \
        ${pkgs.kdePackages.plasma-workspace}/bin/startplasma-wayland "$@"
    ''
  );
  xdg.portal = {
    enable = true;
    extraPortals = [pkgs.xdg-desktop-portal-gtk];
    config.common.default =
      if cfg.plasma.enable
      then "kde"
      else "gtk";
    config.gtk.default = "gtk";
  };

  # NIX_XDG_DESKTOP_PORTAL_DIR gates which portal backends the frontend can
  # even see; it was defaulting to the per-user profile (hyprland.portal
  # only), so cosmic/gnome/kde sessions got PortalNotFound for Screenshot and
  # Settings. Point it at the system profile, which has every backend.
  systemd.user.services.xdg-desktop-portal.environment.NIX_XDG_DESKTOP_PORTAL_DIR =
    lib.mkForce "/run/current-system/sw/share/xdg-desktop-portal/portals";

  # User avatar for SDDM
  services.accounts-daemon.enable = true;
  system.activationScripts.sddm-avatar = ''
    mkdir -p /var/lib/AccountsService/icons
    cp ${../../assets/profile.png} /var/lib/AccountsService/icons/${username}
    chmod 644 /var/lib/AccountsService/icons/${username}
  '';

  # Keyboard
  services.xserver.xkb = {
    layout = "de";
    variant = "";
  };

  # Fcitx5's built-in Unicode/emoji typing goes through the actual IME input
  # channel (not clipboard+paste), so selecting an emoji types it directly
  # into whatever field has focus — in any toolkit, on any desktop session.
  i18n.inputMethod = {
    enable = true;
    type = "fcitx5";
    # Wayland input-method frontend (text-input-v3) instead of the
    # GTK_IM_MODULE/QT_IM_MODULE shims — every session here is Wayland, and
    # KWin only feeds fcitx5 through the Wayland frontend.
    fcitx5.waylandFrontend = true;
    fcitx5.addons = with pkgs; [fcitx5-gtk kdePackages.fcitx5-qt kdePackages.fcitx5-configtool];
  };

  # Touchpad
  services.libinput = {
    enable = true;
    touchpad = {
      tapping = true;
      naturalScrolling = true;
      disableWhileTyping = true;
      clickMethod = "buttonareas";
    };
    mouse = {
      naturalScrolling = true;
    };
  };

  environment.sessionVariables = {
    GTK_THEME = "Sweet-Dark-v40";
    GTK2_RC_FILES = "${pkgs.sweet-theme}/share/themes/Sweet-Dark-v40/gtk-2.0/gtkrc";
  };

  # Fonts
  fonts.packages = with pkgs; [
    nerd-fonts.meslo-lg
    nerd-fonts.jetbrains-mono
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-color-emoji
  ];

  fonts.fontconfig.defaultFonts = {
    serif = ["Noto Serif"];
    sansSerif = ["Noto Sans"];
    monospace = ["JetBrainsMono Nerd Font"];
    emoji = ["Noto Color Emoji"];
  };
}
